export const DESIGNATIONS = {
  REQUEST: "DESIGNATIONS_REQUEST",
  SUCCESS: "DESIGNATIONS_SUCCESS",
  FAIL: "DESIGNATIONS_FAIL",
};

export const REGISTER = {
  REQUEST: "REGISTER_REQUEST",
  SUCCESS: "REGISTER_SUCCESS",
  FAIL: "REGISTER_FAIL",
  RESET: "REGISTER_RESET",
};

export const LOGIN = {
  REQUEST: "LOGIN_REQUEST",
  SUCCESS: "LOGIN_SUCCESS",
  FAIL: "LOGIN_FAIL",
  RESET: "LOGIN_RESET",
  FAIL_RESET: "LOGIN_FAIL_RESET",
};

export const USER_WEEKLY_MENU = {
  REQUEST: "USER_WEEKLY_MENU_REQUEST",
  SUCCESS: "USER_WEEKLY_MENU_SUCCESS",
  FAIL: "USER_WEEKLY_MENU_FAIL",
};

export const PLANS = {
  REQUEST: "PLANS_REQUEST",
  SUCCESS: "PLANS_SUCCESS",
  FAIL: "PLANS_FAIL",
};

export const CHECK_SUBSCRIPTION = {
  REQUEST: "CHECK_SUBSCRIPTION_REQUEST",
  SUCCESS: "CHECK_SUBSCRIPTION_SUCCESS",
  FAIL: "CHECK_SUBSCRIPTION_FAIL",
  RESET: "CHECK_SUBSCRIPTION_RESET",
};

export const SUBSCRIBE_NOW = {
  REQUEST: "SUBSCRIBE_NOW_REQUEST",
  SUCCESS: "SUBSCRIBE_NOW_SUCCESS",
  FAIL: "SUBSCRIBE_NOW_FAIL",
  RESET: "SUBSCRIBE_NOW_RESET",
};

export const INVOICE = {
  REQUEST: "INVOICE_REQUEST",
  SUCCESS: "INVOICE_SUCCESS",
  FAIL: "INVOICE_FAIL",
  RESET: "INVOICE_RESET",
};

export const INVOICE_UPLOAD = {
  REQUEST: "INVOICE_UPLOAD_REQUEST",
  SUCCESS: "INVOICE_UPLOAD_SUCCESS",
  FAIL: "INVOICE_UPLOAD_FAIL",
  RESET: "INVOICE_UPLOAD_RESET",
};

export const MEAL_CANCEL = {
  REQUEST: "MEAL_CANCEL_REQUEST",
  SUCCESS: "MEAL_CANCEL_SUCCESS",
  FAIL: "MEAL_CANCEL_FAIL",
  RESET: "MEAL_CANCEL_RESET",
};

export const MEAL_CANCEL_LIST = {
  REQUEST: "MEAL_CANCEL_LIST_REQUEST",
  SUCCESS: "MEAL_CANCEL_LIST_SUCCESS",
  FAIL: "MEAL_CANCEL_LIST_FAIL",
};

export const ADD_WEEKLY_MENU = {
  REQUEST: "ADD_WEEKLY_MENU_REQUEST",
  SUCCESS: "ADD_WEEKLY_MENU_SUCCESS",
  FAIL: "ADD_WEEKLY_MENU_FAIL",
  RESET: "ADD_WEEKLY_MENU_RESET",
};

export const ALL_WEEKLY_MENUS = {
  REQUEST: "ALL_WEEKLY_MENUS_REQUEST",
  SUCCESS: "ALL_WEEKLY_MENUS_SUCCESS",
  FAIL: "ALL_WEEKLY_MENUS_FAIL"
};

export const ALL_USERS = {
  REQUEST: "ALL_USERS_REQUEST",
  SUCCESS: "ALL_USERS_SUCCESS",
  FAIL: "ALL_USERS_FAIL"
};

export const ADMIN_INVOICES = {
  REQUEST: "ADMIN_INVOICES_REQUEST",
  SUCCESS: "ADMIN_INVOICES_SUCCESS",
  FAIL: "ADMIN_INVOICES_FAIL"
};

export const VERIFY_INVOICE = {
  REQUEST: "VERIFY_INVOICE_REQUEST",
  SUCCESS: "VERIFY_INVOICE_SUCCESS",
  FAIL: "VERIFY_INVOICE_FAIL",
  RESET: "VERIFY_INVOICE_RESET",
};

export const ADMIN_MEAL_CANCEL_LIST = {
  REQUEST: "ADMIN_MEAL_CANCEL_LIST_REQUEST",
  SUCCESS: "ADMIN_MEAL_CANCEL_LIST_SUCCESS",
  FAIL: "ADMIN_MEAL_CANCEL_LIST_FAIL"
};
